# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 92e5d6b70bd0497c7b5fed413aed9619a20548f8cc7527d05282c3b2a136a0cdb044e163b8c96b365c477a50ad96bdd31fc0691d01ef995893af848d93d7e06b

test:
  secret_key_base: e09d1820c56ebdd6999f2a5443e10ad51e36db1058355a08428899a20dc9793cce43728217139854b7b1a6db6403c044d5ce59bf4d4a611e53a637f2aadcf1f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
